debug: false

spring:
  profiles:
    active: prop 
  datasource: 
    url: jdbc:mysql://localhost:3306/animus
    username: root
    password: jh1110
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

---
#开发环境配置    
spring:
  profiles: dev

server:
  port: 8010
  address: 127.0.0.1
  contextPath: /

---
#测试环境配置    
spring:
  profiles: test
  
---
#生产环境设置
spring:
  profiles: prop

server:
  port: 80
  address: 127.0.0.1
  contextPath: /